### ISSUE TITLE
Is the official jolokia plugin not enough?

### ISSUE THREAD

**Issue by xrl** [paksu/kafka-jolokia-telegraf-collector#1]
Does the work in this code address a deficiency in https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia ?

**Comment by ththvseo** [comment]
after finding out the hard way:
* the `jolokia` plugin included with telegraf is practically unusable for collecting kafka metrics. (see https://github.com/influxdata/telegraf/issues/2014 )
* a replacement `jolokia2` is coming up at https://github.com/influxdata/telegraf/pull/2278

in the meantime, the code in this project might be a viable solution.
